name: retention_indices
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - bottleneck=1.3.4=py37h67323c0_0
  - ca-certificates=2022.3.18=hecd8cb5_0
  - catboost=0.26.1=py37hecd8cb5_0
  - certifi=2021.10.8=py37hecd8cb5_2
  - intel-openmp=2021.4.0=hecd8cb5_3538
  - joblib=1.1.0=pyhd3eb1b0_0
  - libcxx=12.0.0=h2f01273_0
  - libffi=3.3=hb1e8313_2
  - libgfortran=3.0.1=h93005f0_2
  - llvm-openmp=12.0.0=h0dcd299_1
  - mkl=2021.4.0=hecd8cb5_637
  - mkl-service=2.4.0=py37h9ed2024_0
  - mkl_fft=1.3.1=py37h4ab4a9b_0
  - mkl_random=1.2.2=py37hb2f4e1b_0
  - ncurses=6.3=hca72f7f_2
  - numexpr=2.8.1=py37h2e5f0a9_0
  - numpy=1.21.2=py37h4b4dc7a_0
  - numpy-base=1.21.2=py37he0bd621_0
  - openssl=1.1.1n=hca72f7f_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.3.4=py37h743cdd8_0
  - pip=21.2.2=py37hecd8cb5_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - python=3.7.11=h88f2d9e_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytz=2021.3=pyhd3eb1b0_0
  - readline=8.1.2=hca72f7f_1
  - scikit-learn=1.0.2=py37hae1ba45_1
  - scipy=1.7.3=py37h8c7af03_0
  - setuptools=58.0.4=py37hecd8cb5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.37.2=h707629a_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.11=h7bc2e8c_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h1de35cc_0
  - zlib=1.2.11=h4dc903c_4
prefix: /Users/jimboelrijk/opt/anaconda3/envs/retention_indices
